# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
    tags:
      - v*.*.*
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          # - os: windows
          #   arch: amd64
          #   suffix: .exe
          # - os: windows
          #   arch: arm64
          #   suffix: .exe

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o gron-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.suffix || '' }}

      - name: Test
        run: go test -v ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gron-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.suffix || '' }}
          path: gron-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.suffix || '' }}

      - name: Release
        uses: softprops/action-gh-release@v2.2.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: gron-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.suffix || '' }}
          generate_release_notes: false
